---
- :vi
- :compute
- :conf
- :svc
- :clo
- :inf
- :con
- :sto
- :cnt
- :aut
- :opt
- :net
- :set
- :accessInsights
- :external_menu
- ems-type:atomic_enterprise
- ems-type:azure
- ems-type:azure_network
- ems-type:ec2
- ems-type:ec2_network
- ems-type:gce
- ems-type:foreman_configuration
- ems-type:foreman_provisioning
- ems-type:openshift_enterprise
- ems-type:openstack
- ems-type:openstack_network
- ems-type:openstack_infra
- ems-type:rhevm
- ems-type:scvmm
- ems-type:vmwarews
- ems-type:vmware_cloud
